### ISSUE TITLE
form_barycentric function using different assumption from simplex_basis

### ISSUE THREAD

**Issue by jacobmerson** [sandialabs/omega_h#389]
The code to construct the simplex basis here: https://github.com/sandialabs/omega_h/blob/f44edbb568b5acf4bed25f8f9bd3df2c6d0ab869/src/Omega_h_shape.hpp#L13-L18

Forms the basis with respect to xi_1 and xi_2 (for triangles). But, the `form_barycentric` function here:
https://github.com/sandialabs/omega_h/blob/f44edbb568b5acf4bed25f8f9bd3df2c6d0ab869/src/Omega_h_shape.hpp#L43-L52

assumes that the input is xi_0 and xi_1 (for triangles) and thus the resulting barycentric coordinates are improperly rotated.

The fix for `form_barycentric` is trivial, but I'm not sure how that will impact its uses in `Omega_h_confined.cpp` and `Omega_h_transfer.cpp`.

I will submit a pull request with a test that indicates the problem with `form_barycentric` shortly.

**Comment by ibaned** [comment]
Why is this a problem exactly?

**Comment by jacobmerson** [comment]
I'll write it out in 2D to reduce the effort, but the same issue exists in higher dimensions:

the `simplex_basis` function is computed as not sure how to write math here so it's a bit clunky.:

[ (x_1-x_0) (x_2-x_0)] [xi_1] = [x-x_0]
[ (y_1-y_0) (y_2-y_0)] [xi_2] = [y-y_0]

Or, 

T . xi = x-x_0

So, here we see that if we take T^-1 . (x-x_0) gives the xi_1 and xi_2 parametric coordinates related to the nodes 1 and 2. But, the `form_barycentric` function assumes that the parametric coordinates as inputs are xi_0 and xi_1 from nodes 0 and 1. So,  there is a mismatch between which parametric coordinates are expected. This means if the output from the `simplex_basis` is used with the `form_barycentric` function then the parametric coordinates are permuted from what they should be.

Does this clarify things?

**Comment by ibaned** [comment]
I see, you're trying to combine these two to convert a point in the global coordinate space into a point in the local parametric space...

I just read `Omega_h_confined` and `Omega_h_transfer`, and both uses actually seem to be doing that too! (In fact... it is possible that `Omega_h_transfer` suffers from a bug due to the inconsistency you're pointing out, and `Omega_h_confined` happens to be agnostic luckily).

I would propose the following:
1. Fix `form_barycentric`, make it work the way you are suggesting
2. Provide a new API function that takes the global coordinates of the vertices of a simplex and an arbitrary global coordinate point and returns the barycentric coordinates of the arbitrary point
3. Use that new API function in `Omega_h_confined` and `Omega_h_transfer`

Would you be able to do some of this work @jacobmerson ?

**Comment by jacobmerson** [comment]
Sure I agree with your breakdown. I will do parts 1 and 2 and make an attempt to do part 3. I'll provide tests for 1/2 and I'll definitely need @ibaned to at least review part 3 if not create a test case.

**Comment by ibaned** [comment]
Sounds good I can test your branch once you've done that!

**Comment by jacobmerson** [comment]
Quick question. A bunch of these functions are passing structs like `Vector<dim>` by value. Normally I would pass anything larger than a `uintptr_t` by const reference (or where it makes sense overloads for r-value references). I'm tempted to change simplex_basis and form barycentric to take by reference. Do you have strong feelings on this? At least for my usage computing the barycentric from global will be inside a hot loop, so maybe it's worth profiling.

**Comment by ibaned** [comment]
Passing by const reference is fine by me, that's what I usually do by default today. A lot of Omega_h uses pass by value, and we can change it "as we go" like you're doing since you're refactoring these functions anyways or profile-guided (focus on the functions that are called from kernels that take a long time).

**Comment by ibaned** [comment]
This has been fixed, please comment if it's still an issue.
